### ISSUE TITLE
can't run train file

### ISSUE THREAD

**Issue by jiaowei123456** [BruceResearch/BiTr-Unet#3]
i use correct path of my training data,but can't run the train.py,the following is my log:
(my-env) root@autodl-container-22d9119dfa-7f3a08d0:~/autodl-tmp/BiTr-Unet# python3 -m torch.distributed.launch --nproc_per_node=2 --master_port 20003 train.py
2023-04-16 11:40:11 ===> --------------------------------------This is all argsurations----------------------------------
2023-04-16 11:40:11 ===> user=name of user
2023-04-16 11:40:11 ===> experiment=BiTrUnet
2023-04-16 11:40:11 ===> date=2023-04-16
2023-04-16 11:40:11 ===> description=TransBTS,training on train.txt!
2023-04-16 11:40:11 ===> main_path=./
2023-04-16 11:40:11 ===> root=./data
2023-04-16 11:40:11 ===> train_dir=/BraTS2021_TrainingData
2023-04-16 11:40:11 ===> valid_dir=/BraTS2021_ValidationData
2023-04-16 11:40:11 ===> mode=train
2023-04-16 11:40:11 ===> train_file=train.txt
2023-04-16 11:40:11 ===> valid_file=official_valid.txt
2023-04-16 11:40:11 ===> dataset=brats
2023-04-16 11:40:11 ===> model_name=BiTrUnet
2023-04-16 11:40:11 ===> input_C=4
2023-04-16 11:40:11 ===> input_H=240
2023-04-16 11:40:11 ===> input_W=240
2023-04-16 11:40:11 ===> input_D=160
2023-04-16 11:40:11 ===> crop_H=128
2023-04-16 11:40:11 ===> crop_W=128
2023-04-16 11:40:11 ===> crop_D=128
2023-04-16 11:40:11 ===> output_D=155
2023-04-16 11:40:11 ===> lr=0.0002
2023-04-16 11:40:11 ===> weight_decay=1e-05
2023-04-16 11:40:11 ===> amsgrad=True
2023-04-16 11:40:11 ===> criterion=Generalized_dice
2023-04-16 11:40:11 ===> num_class=4
2023-04-16 11:40:11 ===> seed=1000
2023-04-16 11:40:11 ===> no_cuda=False
2023-04-16 11:40:11 ===> gpu=0,1
2023-04-16 11:40:11 ===> num_workers=8
2023-04-16 11:40:11 ===> batch_size=8
2023-04-16 11:40:11 ===> start_epoch=0
2023-04-16 11:40:11 ===> end_epoch=3000
2023-04-16 11:40:11 ===> save_freq=50
2023-04-16 11:40:11 ===> resume=
2023-04-16 11:40:11 ===> load=True
2023-04-16 11:40:11 ===> local_rank=0
2023-04-16 11:40:11 ===> ----------------------------------------This is a halving line----------------------------------
2023-04-16 11:40:11 ===> TransBTS,training on train.txt!
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main_worker()
  File "train.py", line 131, in main_worker
    _, model = BiTrUnet(dataset='brats', _conv_repr=True, _pe_type="learned")
  File "/root/autodl-tmp/BiTr-Unet/models/BiTrUnet/BiTrUnet.py", line 501, in BiTrUnet
    positional_encoding_type=_pe_type,
  File "/root/autodl-tmp/BiTr-Unet/models/BiTrUnet/BiTrUnet.py", line 251, in __init__
    Traceback (most recent call last):
positional_encoding_type=positional_encoding_type,
  File "train.py", line 282, in <module>
TypeError: __init__() got an unexpected keyword argument 'img_dim'
    main_worker()
  File "train.py", line 131, in main_worker
    _, model = BiTrUnet(dataset='brats', _conv_repr=True, _pe_type="learned")
  File "/root/autodl-tmp/BiTr-Unet/models/BiTrUnet/BiTrUnet.py", line 501, in BiTrUnet
    positional_encoding_type=_pe_type,
  File "/root/autodl-tmp/BiTr-Unet/models/BiTrUnet/BiTrUnet.py", line 251, in __init__
    positional_encoding_type=positional_encoding_type,
TypeError: __init__() got an unexpected keyword argument 'img_dim'
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main_worker()
  File "train.py", line 131, in main_worker
    _, model = BiTrUnet(dataset='brats', _conv_repr=True, _pe_type="learned")
  File "/root/autodl-tmp/BiTr-Unet/models/BiTrUnet/BiTrUnet.py", line 501, in BiTrUnet
    positional_encoding_type=_pe_type,
  File "/root/autodl-tmp/BiTr-Unet/models/BiTrUnet/BiTrUnet.py", line 251, in __init__
    positional_encoding_type=positional_encoding_type,
TypeError: __init__() got an unexpected keyword argument 'img_dim'
Traceback (most recent call last):
  File "/root/miniconda3/envs/my-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/my-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/my-env/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/root/miniconda3/envs/my-env/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/my-env/bin/python3', '-u', 'train.py', '--local_rank=1']' returned non-zero exit status 1.

i dont know how to revise it, look forward to your reply

**Comment by Z-TTY** [comment]
I have also encountered this problem, have you solved it please?

**Comment by C-Annapurna** [comment]
I also encountered this problem，any solutions?

**Comment by SkAdilina** [comment]
I get the same error :(

**Comment by Hang3Y** [comment]
omg, the same error!

**Comment by listener114** [comment]
same error！！ have you fix it？
